# Generated by Django 4.2.3 on 2023-07-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="user_info",
            fields=[
                (
                    "handle",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("rank", models.CharField(blank=True, max_length=30, null=True)),
                ("updated_at", models.DateTimeField()),
            ],
        ),
    ]
