# Generated by Django 4.2.3 on 2023-08-01 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("query", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="user_rating",
            fields=[
                ("user_rating_id", models.AutoField(primary_key=True, serialize=False)),
                ("contest_id", models.IntegerField()),
                ("contest_name", models.CharField(max_length=255)),
                ("rank", models.IntegerField()),
                ("old_rating", models.IntegerField()),
                ("new_rating", models.IntegerField()),
                ("rating_updated_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "handle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="query.user_info",
                    ),
                ),
            ],
        ),
    ]
